# Generated by Django 6.0.3 on 2026-05-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
        ('membro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membru',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.status', verbose_name='Status'),
        ),
    ]
