# Generated by Django 6.0.3 on 2026-05-07 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0002_alter_membru_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membru',
            name='appr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distappr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membru',
            name='conf_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distconf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membru',
            name='date_appr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membru',
            name='date_conf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membru',
            name='is_appr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membru',
            name='is_conf',
            field=models.BooleanField(default=False),
        ),
    ]
