# Generated by Django 6.0.3 on 2026-05-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0003_membru_appr_by_membru_conf_by_membru_date_appr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membru',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='membru',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='membru',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='membru',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='membru',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='membru',
            name='updated_by',
        ),
    ]
