# Generated by Django 6.0.3 on 2026-05-07 11:29

import django.db.models.deletion
import django.utils.timezone  # <-- tambah import ini
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0004_remove_membru_created_at_remove_membru_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membru',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),  # <-- ganti ini
        ),
        migrations.AddField(
            model_name='membru',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membru',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membru',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membru',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),  # <-- ganti ini juga
        ),
        migrations.AddField(
            model_name='membru',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]