# Generated by Django 6.0.3 on 2026-05-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0005_membru_created_at_membru_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membru',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membru',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
