# Generated by Django 6.0.3 on 2026-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0006_alter_membru_created_at_alter_membru_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membru',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membru',
            name='hashed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
