# Generated by Django 6.0.3 on 2026-05-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membro', '0007_alter_membru_datetime_alter_membru_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaleducation',
            name='university',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universidade/Entidade'),
        ),
    ]
